spring.datasource.url=jdbc:mysql://localhost:3306/peluchesdb
spring.datasource.username=root
spring.datasource.password=Lunaysol11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false